{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-secret"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: "{{ .Values.vault.secretStoreName }}"

  target:
    name: "{{ .Release.Name }}-secret"
    creationPolicy: Owner

  {{- with .Values.vault.vaultSecrets }}
  data:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}