{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "ob-service.fullname" . }}
  labels:
    {{- include "ob-service.labels" . | nindent 4 }}
data:
  {{- with .Values.secrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}