{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ob-service.fullname" . }}
  labels:
    {{- include "ob-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "ob-service.selectorLabels" . | nindent 4 }}
{{- end }}